name: beeline_retail_monorepo

sdkPath: .fvm/flutter_sdk

packages:
  - packages/**
  - apps/**

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze:
    exec: flutter analyze .
  outdated:
    exec: flutter pub outdated
  test:
    exec: flutter test

  ## Generate derivate files
  generate:common:
    run: melos exec --fail-fast --scope="*common*" --flutter -- "flutter pub run build_runner build --delete-conflicting-outputs"
  generate:common_dol:
    run: melos exec --fail-fast --scope="*common_dol*" --flutter -- "flutter pub run build_runner build --delete-conflicting-outputs"
  generate:conf:
    run: melos exec --fail-fast --scope="*conf*" --flutter -- "fvm flutter pub run build_runner build --delete-conflicting-outputs"
  generate:contracts:
    run: melos exec --fail-fast --scope="*contracts*" --flutter -- "fvm flutter pub run build_runner build --delete-conflicting-outputs"
  generate:ao:
    run: melos exec --fail-fast --scope="*ao*" --flutter -- "fvm flutter pub run build_runner build --delete-conflicting-outputs"
  generate:dol:
    run: melos exec --fail-fast --scope="*dol*" --flutter -- "fvm flutter pub run build_runner build --delete-conflicting-outputs"
  generate:all:
    run: melos exec --fail-fast --depends-on="build_runner" --flutter -- "fvm flutter pub run build_runner build --delete-conflicting-outputs"
  ##

  ## Сборка/запуск приложений
  build:dol:
    run: melos exec --fail-fast --scope="*dol*" --flutter -- "fvm flutter build"
  run:pro:
    run: melos exec --fail-fast --scope="*dol*" --flutter -- "fvm flutter run"

  ## Сборка/релиз Android
  build:dol:apk:
    run: melos exec --fail-fast --flutter -- "fvm flutter build apk --no-tree-shake-icons --release"
    packageFilters:
      dirExists:
        - android
      scope: "*dol*"

  build:dol:appbundle:
    run: melos exec --fail-fast --flutter -- "fvm flutter build appbundle --no-tree-shake-icons --release"
    packageFilters:
      dirExists:
        - android
      scope: "*dol*"