name: dol
description: "Example Flutter Modules"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  common:
    path: ../../packages/common
  common_dol:
    path: ../../packages/common_dol
  conf:
    path: ../../packages/conf
  contracts:
    path: ../../packages/contracts
  ao:
    path: ../../packages/ao
  uikit:
    path: ../../packages/uikit

  get_it: ^7.6.7
  auto_route: ^8.0.3

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  auto_route_generator: ^8.0.0
  rx_notifier: ^1.1.0
  flutter_screenutil: ^5.5.3+2

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
