name: ao
description: "AO Module"
version: 0.0.1

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  auto_route: ^8.0.3
  rx_notifier: ^1.1.0
  flutter_screenutil: ^5.5.3+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  auto_route_generator: ^8.0.0
