name: contracts
description: "CONTRACTS Module"
version: 0.0.1

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  common:
    path: ../../packages/common
  common_dol:
    path: ../../packages/common_dol
  json_annotation: ^4.8.1
  rx_notifier: ^1.1.0
  flutter_screenutil: ^5.5.3+2
  auto_route: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  auto_route_generator: ^8.0.0
